package android;
public final class Manifest { public static final class permission { public static final String BLUETOOTH_SCAN="BLUETOOTH_SCAN", BLUETOOTH_ADVERTISE="BLUETOOTH_ADVERTISE", BLUETOOTH_CONNECT="BLUETOOTH_CONNECT", ACCESS_FINE_LOCATION="ACCESS_FINE_LOCATION", NEARBY_WIFI_DEVICES="NEARBY_WIFI_DEVICES"; } }
